global:
    scrape_interval: 15s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "loggate"
      static_configs:
          - targets: ["loggate:9100"]

    - job_name: "loki"
      static_configs:
          - targets: ["loki:3100"]

    - job_name: "promtail"
      static_configs:
          - targets: ["promtail:9080"]

    - job_name: "cadvisor"
      static_configs:
          - targets: ["cadvisor:8080"]
