server:
    listen_address: ":10514"
    metrics_address: "0.0.0.0:9100"

storages:
    - type: "console"
      enabled: true

    - type: "clickhouse"
      enabled: false
      dsn: "clickhouse://<user>:<password>@<host>:<port>/<database>?[params]"

    - type: "elasticsearch"
      enabled: false
      addresses: ["http://elasticsearch:9200"]

    - type: "influxdb"
      enabled: false
      url: "http://influxdb:8086"
      token: "my-secret-token"
      org: "my-org"
      bucket: "logs"
