{
 "title": "LogGate Application",
 "tags": [
  "loggate",
  "provisioned"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service_name)" },
   { "name": "level", "query": "info,warn,error,debug,trace" },
   { "name": "level_filter", "query": "${level:regex}" }
  ]
 },
 "panels": [
  {
   "title": "Информация",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## LogGate Application Dashboard\n*   **Фильтруйте** данные с помощью переменных вверху экрана.\n*   **Исследуйте** метрики производительности и логи приложения."
   }
  },
  { "title": "Key Metrics & Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Log Rate (lines/sec)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"docker_logs\", service_name=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate (errors/sec)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"docker_logs\", service_name=~\"$service\"} |~ `(?i)error|crit|fatal` [1m]))"
    }
   ]
  },
  {
   "title": "Loggate Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"loggate\"}"
    }
   ]
  },
  {
   "title": "Loggate Memory (Alloc)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"loggate\"}"
    }
   ]
  },
  {
   "title": "Log Volume by Level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"docker_logs\", service_name=~\"$service\"} |~ \"$level_filter\" [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Live Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"docker_logs\", service_name=~\"$service\"} |~ \"$level_filter\""
    }
   ]
  }
 ]
}